relativeURLs = true
baseURL = "/"
googleAnalytics = "UA-24864834-6"
title = "Lei's Blog"
languageCode = "zh-cn"
hasCJKLanguage = true
theme = "hyde"
[params]
    description = "科研、生活、技术的记录"
    copyright = "Copyright © 2010-2018 Lei Yang"
